---
title: "Growth vs death change in abundance figure"
author: "Cassandra Wattenburger"
date: "07/24/2024"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(results = "show")
knitr::opts_chunk$set(message = FALSE)
```

```{r}
# Clear working directory, load in packages, generate package info
rm(list=ls())

library("tidyverse")

sessionInfo()
```

# Import and prep data

```{r}
growth <- readRDS("../data_intermediate/NIFA_grests_final_ind.rds")
pap <- readRDS("../data_intermediate/NIFA_paprica_ests.rds")

growth_pap <- inner_join(growth, pap) %>% 
  mutate(Replicate = as.character(Replicate))

growth_asv <- growth_pap %>% # average replicates
  group_by(Soil, ASV) %>% 
  summarize_if(is.numeric, mean) %>% 
  ungroup()

death <- readRDS("../data_intermediate/NIFA_dests_final_ind.rds")
head(death)

# Average across reps
death_asv <- death %>% 
  mutate(Replicate = as.character(Replicate)) %>% 
  group_by(Soil, ASV) %>% 
  summarize_if(is.numeric, mean) %>% 
  ungroup()

# Combine growth and death
deltaN <- death_asv %>% 
  select(Soil, ASV, change_death = change_abund) %>% 
  inner_join(growth_asv) %>% 
  mutate(deltaNd = change_death/n16S,
         deltaNg = change_abund/n16S) %>% 
  select(Soil, ASV, deltaNg, deltaNd)
```

# Visualize

```{r}
deltaN_isme <- deltaN %>% 
  ggplot(aes(x=log(deltaNg), y=log(abs(deltaNd)))) +
  geom_point(size=2, shape=1) +
  geom_smooth(method="lm", color="black", linetype=2) +
  facet_wrap(~Soil, nrow=2, scales="free") +
  theme_test() +
  theme(axis.text=element_text(size=7),
        axis.title=element_text(size=7),
        strip.text = element_blank())
deltaN_isme

# Stats
cor.test(log(deltaN[deltaN$Soil=="Ag",]$deltaNg), log(abs(deltaN[deltaN$Soil=="Ag",]$deltaNd)), method="pearson")
cor.test(log(deltaN[deltaN$Soil=="Meadow",]$deltaNg), log(abs(deltaN[deltaN$Soil=="Meadow",]$deltaNd)), method="pearson")
```

```{r, eval=FALSE}
ggsave(deltaN_isme, file="../figures/fig_deltaNgd_isme.svg", units="mm", width=85, height=150, device="svg")
```



