---
title: "NIFA_scraps.Rmd"
author: "Cassandra Wattenburger"
date: "1/11/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# From NIFA_growthestimation.Rmd

Notes: tried fitting to non-linear model but couldn't get it to work. See below.

Fit expnential-plateau model:

```{r, eval=FALSE}
set.seed(1)
library(nlraa)
fit_nls <- nls(false ~ SSexpfp(pvalue, a, c, xs), data=false_pos)
new_pvals <- data.frame(pvalue=seq(0, 0.02, by=0.0001))
pred_nls <- predict(fit_nls, newdata=new_pvals)

# Create dataframe of predicted values
pred_vals <- data.frame(false_pos = pred_nls, pvalue = new_pvals)

ggplot(pred_vals, aes(x=pvalue, y=false_pos)) +
  geom_point()
```

That isn't an exponential plateau, SSexpfp...

----

Shorter estimates look spurious, let's look at more...

```{r}
short_ests <- growth_falsepos10 %>% 
  mutate(length=end-start) %>% 
  filter(length < 4)

# 10% false positive rate
labels_short <- as.character(short_ests$label)

# Randomly plot 10 w/growth estimate
for (n in 1:10) {
  # Choose randomly
  rand_num <- sample(1:nrow(short_ests), 1)
  l <- labels_short[rand_num]
  
  # Estimated growth window
  start <- short_ests %>% 
    filter(label==l) %>% 
    .$start
  
  end <- short_ests %>% 
    filter(label==l) %>% 
    .$end
  
  # Plot
  data_sub <- norm_prepped %>% 
    filter(label == l)
  plot <- data_sub %>% 
    ggplot(aes(x=time, y=abund)) +
    geom_smooth(method="lm", data=data_sub[start:end,], linetype=2) +
    geom_point() +
    geom_line() +
    theme_test()
  print(plot)
}
```