---
title: "FullCyc2 incorporators"
author: "Cassandra Wattenburger"
date: "3/15/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(results = "show")
knitr::opts_chunk$set(message = FALSE)
```

```{r}
# Clear working directory, load in packages, generate package info
rm(list=ls())

library("tidyverse")

sessionInfo()
```

# Import data

```{r}
incorp <- readRDS("../mothur_cluster/fullcyc2_l2fc_testoutput.rds")

incorp
```


```{r}
# Reformat
incorp2 <- incorp %>% 
  mutate(ecosystem = gsub(".substrate == '12C-Con' & day == '[0-9]+' & ecosystem == '([a-z]+)'.+", "\\1", .id), # separate out .id column info
         day = gsub(".substrate == '12C-Con' & day == '([0-9]+)' .+", "\\1", .id),
         substrate = gsub(".+substrate == '13C-([a-z]+)'.+", "\\1", .id, ignore.case=T),
         substrate = case_when(substrate=="Pal" ~ "palmitic acid", # double check these with Sam!!!
                               substrate=="Ami" ~ "amino acid",
                               substrate=="Xyl" ~ "xylose",
                               substrate=="Cel" ~ "cellulose",
                               substrate=="Van" ~ "vanillin")) %>%
  select(OTU, ecosystem, day, substrate, log2FoldChange, padj) %>% 
  filter(padj < 0.05) # filter incorporators
  
incorp2
```

Save:

```{r, eval=FALSE}
saveRDS(incorp2, file="../data_intermediate/fullcyc2_incorp.rds")
```



Create list of incorporator OTUs:

```{r, eval=FALSE}
incorp_otus <- select(incorp2, OTU) %>% 
  unique()

write_tsv(incorp_otus, "../mothur_cluster/incorp_otus.txt")
```

Create list of growing taxa from NIFA experiment:

```{r, eval=FALSE}
growth_asvs <- readRDS("../data_intermediate/NIFA_grests_final_ind.rds") %>% 
  select(ASV) %>% 
  unique()

write_tsv(growth_asvs, "../mothur_cluster/growth_asvs.txt")
```

Mothur kludger:

```{r}
dist <- read_csv("../mothur_cluster/fixed_alignment_dist2.csv", col_names=FALSE) %>% 
  rename(OTU1=X1, OTU2=X2, dist=X3)

numkey <- read_csv("../mothur_cluster/numberkey_otuasv.csv", col_names=FALSE) %>% 
  rename(num=X1, OTU=X2)

dist2 <- dist %>% 
  full_join(numkey, by=join_by(OTU1==OTU)) %>% 
  rename(num1=num) %>%
  full_join(numkey, by=join_by(OTU2==OTU)) %>% 
  rename(num2=num) %>%
  select(num1, num2, dist) %>% 
  na.omit() # remove coerced NA
```

```{r, eval=FALSE}
write_csv(dist2, file="../mothur_cluster/numkey_dist.csv")
```




