---
title: "Untitled"
author: "Cassandra Wattenburger"
date: "6/22/2023"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(results = "show")
knitr::opts_chunk$set(message = FALSE)
```

```{r}
## Clear working directory, load in packages, generate package info
rm(list=ls())

#library("tidyverse") # deseq2 install broke and can't be bothered to troubleshoot
library("tidyr")
library("magrittr")
library("dplyr")
library("tibble")
library("readr")
library("forcats")
library("ggplot2")

sessionInfo()
```

# Import and reformat data

```{r}
# growth and death estimates
growth <- readRDS("../data_intermediate/NIFA_grests_final_ind.rds") %>% 
  select(Soil, Replicate, ASV, g, gr_start_day=start_day, gr_end_day=end_day, gr_start_abund=start_abund, gr_change_abund=change_abund)

death <- readRDS("../data_intermediate/NIFA_dests_final_ind.rds")%>% 
  select(Soil, Replicate, ASV, h, de_start_day=start_day, de_end_day=end_day, de_start_abund=start_abund, de_change_abund=change_abund)

# Add paprica predictions
pap <- readRDS("../data_intermediate/NIFA_paprica_ests.rds")

growth_pap <- inner_join(growth, pap)
death_pap <- inner_join(death, pap)

# Add cluster
clust <- readRDS("../data_intermediate/NIFA_clusters.rds")

growth_pap_clust <- inner_join(growth_pap, clust)
death_pap_clust <- inner_join(death_pap, clust)

# ASVs that both grew and died
growth_death <- inner_join(growth_pap_clust, death_pap_clust) %>% 
  mutate(gr_start_abund_corr = gr_start_abund/n16S, # correct 16S copies
         gr_change_abund_corr = gr_change_abund/n16S,
         de_start_abund_corr = de_start_abund/n16S,
         de_change_abund_corr = de_change_abund/n16S) %>% 
  group_by(Soil, ASV, cluster) %>% # average reps
  summarise(across(where(is.numeric), ~ mean(.x, na.rm = TRUE))) %>% 
  ungroup()
growth_death
```

# deltaNg vs deltaNd

```{r}
growth_death %>% 
  ggplot(aes(x=abs(de_change_abund_corr), y=gr_change_abund_corr)) +
  geom_point() +
  facet_wrap(~Soil) +
  geom_smooth(method="lm") +
  geom_abline(slope=1, yintercept=0) +
  theme_test()

lm_ag <- lm(log(gr_change_abund_corr) ~ log(abs(de_change_abund_corr)), data=filter(growth_death, Soil=="Ag"))
summary(lm_ag)
lm_meadow <- lm(log(gr_change_abund_corr) ~ log(abs(de_change_abund_corr)), data=filter(growth_death, Soil=="Meadow"))
summary(lm_meadow)

confint(lm_ag, level=0.95)
confint(lm_meadow, level=0.95)
```

