---
title: "NIFA - phylogenetic conservation growth"
author: "Cassandra Wattenburger"
date: "6/27/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r}
library(tibble)
library(dplyr)
library(tidyr)
library(ggplot2)
library(phyloseq)
library(vegan)
library(ape)

sessionInfo()

rm(list=ls())
```

# Import data

```{r}
# Growth estimates
growth <- readRDS("../data_intermediate/NIFA_grests_final_ind.rds")
growth_asv <- growth %>% # average across replicates
  group_by(Soil, ASV) %>% 
  summarize(k = mean(k)) %>% 
  ungroup()

growth_asvs_ag <- growth_asv[growth_asv$Soil=="Ag",]$ASV
growth_asvs_mead <- growth_asv[growth_asv$Soil=="Meadow",]$ASV

# Phyloseq
physeq <- readRDS("../data_intermediate/NIFA_physeq_rare.rds")
```

Isolate tree of growth-estimated taxa:

```{r}
# Isolate tree of growth-inferred taxa
physeq_ag <- subset_taxa(physeq, ASV %in% growth_asvs_ag)
tree_ag <- phy_tree(physeq_ag)

physeq_mead <- subset_taxa(physeq, ASV %in% growth_asvs_mead)
tree_mead <- phy_tree(physeq_mead)

# Calculate phylogenetic distances
phylo_dist_ag <- cophenetic(tree_ag)
phylo_dist_ag[upper.tri(phylo_dist_ag, diag=TRUE)] = NA # remove upper triangle of dist (redundant)

phylo_dist_mead <- cophenetic(tree_mead)
phylo_dist_mead[upper.tri(phylo_dist_mead, diag=TRUE)] = NA # remove upper triangle of dist (redundant)

# Calculate growth rate distances
growth_ag <- growth_asv%>% 
  filter(Soil=="Ag") %>% 
  select(ASV, k) %>% 
  column_to_rownames(var="ASV")

growth_mead <- growth_asv%>% 
  filter(Soil=="Meadow") %>% 
  select(ASV, k) %>% 
  column_to_rownames(var="ASV")

gr_dist_ag <- as.matrix(dist(growth_ag), labels=TRUE)
gr_dist_ag[upper.tri(gr_dist_ag, diag=TRUE)] = NA # remove upper triangle of dist (redundant)

gr_dist_mead <- as.matrix(dist(growth_mead), labels=TRUE)
gr_dist_mead[upper.tri(gr_dist_mead, diag=TRUE)] = NA # remove upper triangle of dist (redundant)

# Mantel correlog
gr_crlg_ag <- mantel.correlog(phylo_dist_ag, gr_dist_ag) # calculate
gr_crlg_ag <- data.frame(gr_crlg_ag$mantel.res) %>% 
  mutate(sig = if_else(Pr.corrected. <= 0.05, "sig", "ns")) %>% 
  filter(!is.na(Pr.corrected.))

gr_crlg_mead <- mantel.correlog(phylo_dist_mead, gr_dist_mead) # calculate
gr_crlg_mead <- data.frame(gr_crlg_mead$mantel.res) %>% 
  mutate(sig = if_else(Pr.corrected. <= 0.05, "sig", "ns")) %>% 
  filter(!is.na(Pr.corrected.))

# Plot
gr_crlg_ag %>% 
  ggplot(aes(x=class.index, y=Mantel.cor, shape=sig)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype=2, color="gray") +
  theme_test()

gr_crlg_mead %>% 
  ggplot(aes(x=class.index, y=Mantel.cor, shape=sig)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype=2, color="gray") +
  theme_test()
```

I don't trust those significant points, given lack of conssistent trend between soils.

# Averaged across soils too

```{r}
growth_asv_both <- growth %>% # average across replicates
  group_by(ASV) %>% 
  summarize(k = mean(k)) %>% 
  ungroup()

growth_asvs <- growth_asv$ASV
```

```{r}
# Isolate tree of growth-inferred taxa
physeq_both <- subset_taxa(physeq, ASV %in% growth_asvs)
tree_both <- phy_tree(physeq_both)

# Calculate phylogenetic distances
phylo_dist_both <- cophenetic(tree_both)
phylo_dist_both[upper.tri(phylo_dist_both, diag=TRUE)] = NA # remove upper triangle of dist (redundant)

# Calculate growth rate distances
growth_both <- growth_asv_both %>% 
  select(ASV, k) %>% 
  column_to_rownames(var="ASV")

gr_dist_both <- as.matrix(dist(growth_both), labels=TRUE)
gr_dist_both[upper.tri(gr_dist_both, diag=TRUE)] = NA # remove upper triangle of dist (redundant)

# Mantel correlog
gr_crlg_both <- mantel.correlog(phylo_dist_both, gr_dist_both) # calculate
gr_crlg_both <- data.frame(gr_crlg_both$mantel.res) %>% 
  mutate(sig = if_else(Pr.corrected. <= 0.05, "sig", "ns")) %>% 
  filter(!is.na(Pr.corrected.))

# Plot
gr_crlg_both %>% 
  ggplot(aes(x=class.index, y=Mantel.cor, shape=sig)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype=2, color="gray") +
  theme_test()
```

